import type { Metadata } from "next";
import { DM_Sans, Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

// DM Sans 에는 한글 글리프가 없어서 한글은 시스템 폰트로 떨어진다.
// 기기와 무관하게 같은 글꼴로 보이도록 한글용 웹폰트를 따로 싣는다.
const notoKR = Noto_Sans_KR({
  variable: "--font-noto-kr",
  // next/font 타입 목록에 korean 이 빠져 있지만 실제로는 한글 subset 을 받아온다.
  // 이걸 빼면 한글이 Noto Sans KR 대신 시스템 폰트로 떨어진다.
  subsets: ["latin", "korean"] as any,
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "steam 상점",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${notoKR.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
